name: 'Update packages'

on:
  schedule:
    # Runs every minute, between 13:00 and 13:59 UTC
    - cron: '* 13 * * *'

  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      GITHUB_TOKEN: "${{ secrets.TOKEN }}"

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        with:
          repository: "${{ github.repository }}"
          token: "${{ env.GITHUB_TOKEN }}"

      - name: 'Install helper programs'
        shell: bash
        run: |
          echo 'Installing helper programs'
          sudo apt update &> /dev/null
          # Python already comes pre-installed so no need to install it again
          sudo apt install -y fd-find sd fish &> /dev/null

          sudo ln -s $(command -v fdfind) /usr/bin/fd

          if ! command -v python &> /dev/null; then
            sudo ln -s $(command -v python3) /usr/bin/python
          fi

          if ! command -v pip &> /dev/null; then
            sudo ln -s $(command -v pip3) /usr/bin/pip
          fi

      - name: 'Update package versions'
        shell: bash
        run: |
          echo 'Installing Python packages'
          pip install -r ./scripts/requirements.txt

          echo '---------------------------------------'
          echo '---------------------------------------'

          for i in $(fd 'update-script' .); do
            chmod +x "$i"
            echo "Executing $i"; eval "$i"
            chmod -x "$i"
            echo '---------------------------------------'
            echo '---------------------------------------'
          done

      - name: Cleanup
        shell: bash
        run: |
          sudo rm $(command -v python) $(command -v pip) $(command -v fd)
          sudo apt remove -y fd-find sd fish &> /dev/null

      - name: 'Commit changes'
        shell: bash
        run: |
          USERNAME='github-actions[bot]'
          EMAIL='41898282+github-actions[bot]@users.noreply.github.com'
          git config --local user.name "$USERNAME"
          git config --local user.email "$EMAIL"
          git add -u
          if [ -n "$(git status --porcelain)" ]; then
            CURRENT_TIME=$(date +'%Y-%m-%d %H:%M:%S')
            git commit -m "bot: Updated packages at $CURRENT_TIME"
          fi

      - name: 'Push changes'
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: "${{ env.GITHUB_TOKEN }}"
          branch: "${{ github.ref }}"
